### ISSUE TITLE
Row overlap in matrix mode

### ISSUE THREAD

**Issue by NilsNemitz** [csdexter/MAX7219#3]
I am using your library to drive a set of three LED matrices. It works great and is fast!

However, when running the MAX7219_matrix example, adjusted for
const MAX7219_Topology topology = {MAX7219_MODE_MATRIX, 0, 0, 2, 7};
the first row of each 8x8 matrix duplicates the last row of the previous matrix.

This is the most obvious in the "rows" part of the demo. In the first seven steps, a single row of LEDs lights up. In the 8th step, two rows are lit, spanning two matrices. This happens again in the 15th step, spanning the 2nd and 3rd matrix.

I have managed to fix this for my application in
void MAX7219::setDigits(const byte *values, byte topo)

by changing
                buf[j] = word(MAX7219_REG_DIGIT0 + 
                              (j ? i : _topology[topo].digitFrom + i),
                              values[(transfers - 1) \* j + i]);

to
                buf[j] = word(MAX7219_REG_DIGIT0 + 
                              (j ? i : _topology[topo].digitFrom + i),
                              values[(transfers - 0) \* j + i]);

(note transfers-0 part)
If this does not break the other operating modes, I would suggest applying that fix to the code in the repository as well ;)

In any case, thanks for your work, it saved me a lot of time!

**Comment by csdexter** [comment]
Thank you for spotting and reporting this. I've performed the change and it appears to perform as described.

Merged in be985b8e11d9fa1cc185bde879fde83f9581a2de
